import Head from 'next/head'

export default function Home () {
  return (
    <div className="min-h-screen p-2 flex flex-col justify-center items-center h-screen">
      <Head>
        <title>URL Shortener</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className="py-20 flex-1 flex flex-col justify-center items-center">
        <h1 className="m-0 leading-tight text-4xl text-center">
          URL Shortener
        </h1>

        <p className="leading-relaxed text-2xl text-center">
          Acorta tus URLs aquí
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-2xl mt-12 w-full flex-col sm:flex-row">
          <form className="m-4 p-6 text-left text-inherit no-underline border border-solid border-gray-300 rounded-xl transition-colors duration-150 ease-in-out hover:text-blue-500 hover:border-blue-500 w-full sm:w-auto">
            <input type='text' className="m-0.5 text-2xl p-4 border border-gray-300 rounded" placeholder='URL' />
            <button className="m-0.5 text-2xl p-4 bg-blue-500 text-white rounded hover:bg-blue-600">
              Acorta
            </button>
          </form>
        </div>
      </main>
    </div>
  )
}
